// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx4wISN5o0x6s0x0I9x9QXoyjwNlNBmPo',
    appId: '1:93808411370:web:0eea72f8b0d30c03248d93',
    messagingSenderId: '93808411370',
    projectId: 'clareco-1f119',
    authDomain: 'clareco-1f119.firebaseapp.com',
    storageBucket: 'clareco-1f119.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrqYVPE09DLmk5efLyMqIxZwE9Fco7lAg',
    appId: '1:93808411370:android:3ed000b0db71e3f1248d93',
    messagingSenderId: '93808411370',
    projectId: 'clareco-1f119',
    storageBucket: 'clareco-1f119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx1zSxWuW8449lmyzqaDFubxEV3_5mYyo',
    appId: '1:93808411370:ios:fba3c1cfe821c6bc248d93',
    messagingSenderId: '93808411370',
    projectId: 'clareco-1f119',
    storageBucket: 'clareco-1f119.appspot.com',
    androidClientId: '93808411370-7fv28tf94jfsploqg35cd9a8kplqpo06.apps.googleusercontent.com',
    iosClientId: '93808411370-6sf22b7ls2eiqepqlklhrc76f1liqshf.apps.googleusercontent.com',
    iosBundleId: 'com.clareco.clareco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx1zSxWuW8449lmyzqaDFubxEV3_5mYyo',
    appId: '1:93808411370:ios:fba3c1cfe821c6bc248d93',
    messagingSenderId: '93808411370',
    projectId: 'clareco-1f119',
    storageBucket: 'clareco-1f119.appspot.com',
    androidClientId: '93808411370-7fv28tf94jfsploqg35cd9a8kplqpo06.apps.googleusercontent.com',
    iosClientId: '93808411370-6sf22b7ls2eiqepqlklhrc76f1liqshf.apps.googleusercontent.com',
    iosBundleId: 'com.clareco.clareco',
  );
}
